### ISSUE TITLE
Release workflow: failing maven deploy due to permission denied

### ISSUE THREAD

**Issue by EricWittmann** [Apicurio/apicurio-data-models#278]
@riprasad You can take a look at the most recent Release workflow for the full log, but here is the line in question:

```
2021-05-21T19:11:16.7392651Z [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project apicurio-data-models: Error while storing the mojo status: /home/runner/work/apicurio-data-models/apicurio-data-models/target/maven-status/maven-compiler-plugin/compile/default-compile/inputFiles.lst (Permission denied) -> [Help 1]
```

Interestingly I got that same permission denied in the workflow when trying to update the package.json file.  I ended up just removing that step from the workflow because it was  no longer necessary.  But apparently it is also a problem when doing the maven deploy.  Any ideas?

**Comment by EricWittmann** [comment]
Link to the release workflow run in question:  https://github.com/Apicurio/apicurio-data-models/actions/runs/864863190

The workflow actually succeeded even though the maven deploy step failed.  Failure was identified by @DyspC here:  https://github.com/Apicurio/apicurio-data-models/pull/272#issuecomment-848738306

**Comment by riprasad** [comment]
@EricWittmann I will take a look at this, but I have some priority items on my to-do list. Might take a while before I pick this one up. Does that work?

**Comment by EricWittmann** [comment]
No problem, @riprasad - I have done the deploy into maven manually for that release, so there's no rush.  I can continue to do that for as long as needed. :)

**Comment by riprasad** [comment]
@EricWittmann The permission denied issues might be because the cloned files are owned by a different user and maven is run as the user that exists in the GitHub actions runner environment. I have now added a step after the code checkout to give full permission to the cloned files to avoid any permission denied issues.

Also, looks like some sleep statements were added to the maven deploy step. But **||** operator was used instead of **&&**. This kind of messed with the retry logic and resulted in false positive. The sleep command was successful and therefore the maven deploy commands after the **||** operator never got executed. I have done the fix and also reduced the sleep time to 30 min for each retry. This is because Github actions has a default timeout set and making it sleep for 4 hours could have resulted in a timeout failure.
